[2025-01-16T03:02:41.522+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion.start_ingestion scheduled__2025-01-15T00:00:00+00:00 [queued]>
[2025-01-16T03:02:41.530+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: data_ingestion.start_ingestion scheduled__2025-01-15T00:00:00+00:00 [queued]>
[2025-01-16T03:02:41.531+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-01-16T03:02:41.531+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-01-16T03:02:41.531+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-01-16T03:02:41.560+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): start_ingestion> on 2025-01-15 00:00:00+00:00
[2025-01-16T03:02:41.567+0000] {standard_task_runner.py:55} INFO - Started process 9475 to run task
[2025-01-16T03:02:41.571+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion', 'start_ingestion', 'scheduled__2025-01-15T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/ingestion/news.py', '--cfg-path', '/tmp/tmptwq_y4sh']
[2025-01-16T03:02:41.573+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask start_ingestion
[2025-01-16T03:02:41.613+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:249 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-16T03:02:41.631+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.10/site-packages/***/utils/sqlalchemy.py:121 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-16T03:02:41.655+0000] {task_command.py:389} INFO - Running <TaskInstance: data_ingestion.start_ingestion scheduled__2025-01-15T00:00:00+00:00 [running]> on host de52c77a285c
[2025-01-16T03:02:41.769+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion
AIRFLOW_CTX_TASK_ID=start_ingestion
AIRFLOW_CTX_EXECUTION_DATE=2025-01-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-01-15T00:00:00+00:00
[2025-01-16T03:03:53.574+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.10/site-packages/spacy/util.py:910 UserWarning: [W095] Model 'en_pipeline' (0.0.0) was trained with spaCy v3.2.0 and may not be 100% compatible with the current version (3.7.6). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
[2025-01-16T03:04:33.900+0000] {logging_mixin.py:137} WARNING - 2025-01-16 03:04:33,900 - INFO - main.py -   Text processed 100 documents
[2025-01-16T03:04:33.900+0000] {main.py:34} INFO - Text processed 100 documents
[2025-01-16T03:04:33.901+0000] {logging_mixin.py:137} INFO - 'NEROut' object has no attribute 'News_Id'
[2025-01-16T03:04:33.901+0000] {logging_mixin.py:137} WARNING - 2025-01-16 03:04:33,901 - INFO - main.py -   Split sentence 0 documents
[2025-01-16T03:04:33.901+0000] {main.py:42} INFO - Split sentence 0 documents
[2025-01-16T03:04:34.355+0000] {milvus_client.py:658} DEBUG - Created new connection using: 4baf10d97e83483593e0f3c1af914bf9
[2025-01-16T03:04:34.356+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.10/site-packages/pymongo/synchronous/mongo_client.py:2554 UserWarning: MongoClient opened before fork. May not be entirely fork-safe, proceed with caution. See PyMongo's documentation for details: https://www.mongodb.com/docs/languages/python/pymongo-driver/current/faq/#is-pymongo-fork-safe-
[2025-01-16T03:04:36.030+0000] {logging_mixin.py:137} WARNING - 2025-01-16 03:04:36,030 - ERROR - main.py -   Failed to process data with error: local variable 'split_sentence_records' referenced before assignment
[2025-01-16T03:04:36.030+0000] {main.py:51} ERROR - Failed to process data with error: local variable 'split_sentence_records' referenced before assignment
[2025-01-16T03:04:36.078+0000] {logging_mixin.py:137} WARNING - 2025-01-16 03:04:36,078 - ERROR - main.py -   Failed to write: isinstance expected 2 arguments, got 1
[2025-01-16T03:04:36.078+0000] {main.py:58} ERROR - Failed to write: isinstance expected 2 arguments, got 1
[2025-01-16T03:04:36.080+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-01-16T03:04:36.087+0000] {taskinstance.py:1322} INFO - Marking task as SUCCESS. dag_id=data_ingestion, task_id=start_ingestion, execution_date=20250115T000000, start_date=20250116T030241, end_date=20250116T030436
[2025-01-16T03:04:36.279+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-01-16T03:04:36.295+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
